name: docker-build

on:
  push:
    branches: ['main']

env:
  DOCKER_IMAGE: #
  DOCKER_CONTAINER: #

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Setup Docker
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}

      - name: build and push image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: #
          port: #
          passphrase: #
          username: #
          password: # 
          key: #
          script: |
            rm .env
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
            cat .env        
            docker stop ${{env.DOCKER_CONTAINER}} && docker rm ${{env.DOCKER_CONTAINER}} && docker rmi ${{env.DOCKER_IMAGE}}:latest
            docker run --env-file ./.env -d -p 3050:3050 --name ${{env.DOCKER_CONTAINER}} --network host --restart always ${{env.DOCKER_IMAGE}}:latest
      
          
